# Generated by Django 4.2.8 on 2024-05-25 09:02

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=250)),
                ('intermediateTravel', models.JSONField(default=list, null=True)),
                ('destination', models.CharField(max_length=250)),
                ('origin_coords', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, srid=4326)),
                ('intermediate_coordsTravel', django.contrib.gis.db.models.fields.GeometryCollectionField(default='GEOMETRYCOLLECTION EMPTY', geography=True, srid=4326)),
                ('destination_coords', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, srid=4326)),
                ('start_date', models.DateTimeField()),
                ('estimated_duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stops', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('completado', 'Completado')], default='programado', max_length=20)),
                ('total_seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intermediate', models.CharField(blank=True, max_length=250, null=True)),
                ('intermediate_coords', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), geography=True, srid=4326)),
                ('seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travel')),
            ],
        ),
    ]
