# Generated by Django 4.2.8 on 2024-05-24 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Travel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=250)),
                ("destination", models.CharField(max_length=250)),
                ("start_date", models.DateTimeField()),
                ("estimated_duration", models.DurationField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stops", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en_curso", "En Curso"),
                            ("completado", "Completado"),
                        ],
                        default="programado",
                        max_length=20,
                    ),
                ),
                (
                    "total_seats",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
            ],
        ),
    ]
