# Generated by Django 4.2.8 on 2024-01-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="travel",
            old_name="passengers_trip",
            new_name="passengers",
        ),
    ]
