# Generated by Django 4.2.8 on 2024-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='travel',
            name='origin',
            field=models.CharField(max_length=250),
        ),
    ]
