# Generated by Django 4.2.8 on 2024-04-13 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_travel_destination_alter_travel_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='total_seats',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
