# Generated by Django 4.2.8 on 2024-01-14 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("travel", "0002_rename_passengers_trip_travel_passengers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="passengers",
            field=models.ManyToManyField(
                blank=True,
                related_name="travels_as_passenger",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
