# Generated by Django 4.2.8 on 2024-01-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_alter_travel_passengers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="travel",
            old_name="host",
            new_name="host_id",
        ),
    ]
