# Generated by Django 4.2.8 on 2024-04-13 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travel_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='total_seats',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
