# Generated by Django 4.2.8 on 2024-01-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_rename_host_travel_host_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="travel",
            old_name="host_id",
            new_name="host",
        ),
    ]
